[package]
name = "esp8266-hal"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
esp8266 = "0.0.3"
nb = "0.1.2"
void = { version = "1.0.2", default-features = false }
embedded-hal = "0.2.3"
