[package]
name = "esp8266-hal"
version = "0.1.0"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"

[dependencies]
esp8266 = { version = "0.0.2" }

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"
