[package]
name = "esp8266-hal"
version = "0.3.2"
authors = ["Robin Appelman <robin@icewind.nl>"]
edition = "2018"
license = "MIT OR Apache-2.0"
description = "An experimental hardware abstraction layer for the esp8266"
repository = "https://github.com/esp-rs/esp8266-hal"
readme = "README.md"

[dependencies]
esp8266 = "0.1.1"
nb = "0.1.2"
void = { version = "1.0.2", default-features = false }
xtensa-lx106-rt = "0.1.0"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.3"

[profile.dev]
lto = true
incremental = false
debug = false # debug adds frame pointers - which must be omitted
codegen-units = 1

[profile.release]
lto = true
incremental = false
debug = false # debug adds frame pointers - which must be omitted
codegen-units = 1